# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Anmol Gupta 
title: Research Scholar at University of Groningen and IIT Roorkee. 
email: agupta@cs.iitr.ac.in
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true


# Social links
twitter_username: chirping_ai
github_username:  binarycache
linkedin_username: anmolscd
additional_links:
- title: Blog
  icon: fab fa-blogger
  url: https://binarycache.github.io/logical_musings/
  
# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Hi, this is Anmol. I am a research scholar doing joint PhD at University of Groningen, Netherlands and IIT Roorkee, India. I work under the supervision of Dr. Partha Pratim Roy, Dr. M.K. Van Vugt and Dr. Niels Taatgen. The topic of my PhD is "Tracking Depression and Elucidating its Mechanisms using Cognitive Neuroscience, EEG, and Machine Learning". It is part of a project approved in the Scheme for Promotion of Academic and Collaboration (SPARC) by MHRD.
 My work includes <mark>Deep Learning</mark>,  <mark> Computational Cognitive Neuroscience </mark> and   <mark>Cognitive Modelling</mark>



content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Joint PhD
        sub_title: University of Groningen and IIT Roorkee
        caption: 2018 - 2022
        qualification: PhD Computer Science
        description: | # this will include new lines to allow paragraphs
           PhD Candidate at University of Groningen, Netherlands and IIT Roorkee, India, under the supervision of Dr. Partha Pratim Roy, Dr. M.K. Van Vugt and Dr. Niels Taatgen. The topic of my PhD is "Tracking Depression and Elucidating its Mechanisms using Cognitive Neuroscience, EEG, and Machine Learning". It is part of a project approved in the Scheme for Promotion of Academic and Collaboration (SPARC) by MHRD, India.
      
      - layout: left
        title: M. Tech.
        sub_title: National Institute of Technology, Hamirpur, India.
        caption: 2014 - 2016
        qualification: M.Tech. Computer Science
        description: | # this will include new lines to allow paragraphs
           CGPA: 9.18, Worked on Automated Layout Generation of a Building using Genetic Algorithms in on order to assist an architect.
 
      - layout: left
        title: B. Tech.
        sub_title: National Institute of Technology, Uttarakhand, India.
        caption: 2010 - 2014
        qualification: B.Tech. Computer Science
        description: | # this will include new lines to allow paragraphs
           CGPA: 8.93
           
      - layout: left
        title: XII | X
        sub_title: SJBSVM, Mathura, India 
        caption: 2009 | 2007
        description: | # this will include new lines to allow paragraphs
           Marks: 89.4% in XII and 91.0% in X.  
      
           
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
