# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Anmol Gupta 
title: PhD Candidate at University of Groningen and IIT Roorkee. 
email: agupta@cs.iitr.ac.in
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: true


# Social links
twitter_username: chirping_ai
github_username:  binarycache
linkedin_username: anmolscd
additional_links:
- title: Blog
  icon: fab fa-blogger
  url: https://binarycache.github.io/logical_musings/
  
# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Hi, this is Anmol. I am a research scholar doing joint PhD at University of Groningen, Netherlands and IIT Roorkee, India. I work under the supervision of Dr. Partha Pratim Roy, Dr. M.K. Van Vugt and Dr. Niels Taatgen. The topic of my PhD is "Tracking Depression and Elucidating its Mechanisms using Cognitive Neuroscience, EEG, and Machine Learning". It is part of a project approved in the Scheme for Promotion of Academic and Collaboration (SPARC) by MHRD.
 My work includes <mark>Deep Learning</mark>,  <mark> Computational Cognitive Neuroscience </mark> and   <mark>Cognitive Modelling</mark>



content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Joint PhD
        sub_title: University of Groningen and IIT Roorkee
        caption: 2018 - 2022
        qualification: PhD Computer Science
        description: | # this will include new lines to allow paragraphs
           Working on identifying and comaring different underlying mechanisms of depression using different modalities like behavioural and neurophysiological.
      
      - layout: left
        title: M. Tech.
        sub_title: National Institute of Technology, Hamirpur, India.
        caption: 2014 - 2016
        qualification: M.Tech. Computer Science
        description: | # this will include new lines to allow paragraphs
           CGPA: 9.18, Worked on Automated Layout Generation of a Building using Genetic Algorithms in on order to assist an architect.
 
      - layout: left
        title: B. Tech.
        sub_title: National Institute of Technology, Uttarakhand, India.
        caption: 2010 - 2014
        qualification: B.Tech. Computer Science
        description: | # this will include new lines to allow paragraphs
           CGPA: 8.93
           
      - layout: left
        title: XII | X
        sub_title: SJBSVM, Mathura, India 
        caption: 2009 | 2007
        description: | # this will include new lines to allow paragraphs
           Marks: 89.4% in XII and 91.0% in X. 
           
  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Eeg-based age and gender prediction using deep blstm-lstm network model
        link: https://scholar.google.com/citations?user=94uEUW0AAAAJ&hl=en&authuser=1
        link_text: Google Scholar
        quote: >
          A Gupta, P Kaushik, PP. Roy and DP. Dogra in IEEE Sensor Letters
        description: | # this will include new lines to allow paragraphs
          We classified age and gender of a person based on the baseline EEG Recordings. An industry standard EEG recording device has been used to record cerebral activities of 60 subjects (both male and female) in relaxed position with closed eyes. Deep BLSTM-LSTM network has been used to construct a hybrid learning framework for the classification. We achieved and accuracy of 93.7% and 97.5% for age and gender classification respectively. Our analysis also reveals that the beta band frequencies are better in predicting the age and gender as compared to other frequency bands of the EEG signals.
     
  - title: Internships and Visits # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Groningen, Netherlands
        link: https://www.rug.nl/staff/m.k.van.vugt/
        # link_text: boringcompany.com
        sub_title: Visiting PhD Candidate
        caption: March 21 - August 21
        quote: >
          Comparing the underlying mechanisms of reward learning and spontaneous thoughts in detecting depression. A cross-national study in India and the USA.
        description: | # this will include new lines to allow paragraphs
            We collected data of 61 participants from India and USA while they were doing the reward learning and spontaneous thinking tasks. We observed that dreward learning is a better phenotype for dignosing depression and there are significant demographic factors that affect the prognosis of depression and closely related constructs like Rumination and Perseverative Thinking.
      
      - layout: left
        title: Bio-Medical Engineering Lab, INMAS, DRDO
        link: https://www.drdo.gov.in/labs-and-establishments/institute-nuclear-medicine-allied-sciences-inmas
        link_text: INMAS, DRDO, India.
        sub_title: Research Intern
        caption: Jul-Nov 2019
        quote: >
          Depression Detection with EEG data and studying the effects of meditation on Depression.
        description: | # this will include new lines to allow paragraphs
            We collected EEG data of 27 Depressed patients before and after meditation (RajaYoga) from KGMC hospital, Karnal. The objective was to observe the before and after differences of meditation on depression and classifying it. We got promising results in differences between the connectivity matrices (PLV) before and after the meditation. The results indicate that decreased activity in the frontal areas of brain. Together with the decreaed questionnaire scores (Hamilton Depression Rating Scale (HDRS)) and the decreased frontal activity, it can be concluded that the mediation actually helped the depressed patients. We are still working on building the classifier.     
      
      - layout: left
        title: ACS Lab, IIT Mandi
        link: http://www.acslab.org/
        link_text: ACS Lab
        sub_title: Research Intern
        caption: Feb-April 2019
        quote: >
          Compared reinforcement learning algorithms; Q-learning and Instance Based Learning. 
        description: | # this will include new lines to allow paragraphs
            We proposed cognitive models like PyIBL as an alternative approach to reinforcement learning. Did a comparison of PyIBL and Q-Learning on FrozenLake environment from OpenAI gym. The results suggest that PyIBL was able to outperform Q-learning in generalizing to a new environment and also took less training time in doing so. (Paper Submitted to IEEE Access)
      
      - layout: left
        title: Osaka Prefecture University, Japan.
        link: http://www.m.cs.osakafu-u.ac.jp/~masa/
        link_text: Osaka Prefecture University
        sub_title: Research Visit
        caption: May 2018
        description: | # this will include new lines to allow paragraphs
           Visited Osaka Prefecture University, Japan under the financial support of JST Sakura Science Plan to have technical discussions in the areas of brain computer interface and deep learning.  
            
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Groningen, Netherlands
        link: https://www.rug.nl/staff/m.k.van.vugt/
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
